apiVersion: v1
kind: ConfigMap
metadata:
  namespace: fuelpay
  name: config-digital-fuel-scheduler-service
data:
  application.yml: |
    management:
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          group:
            custom:
              include: db,ping
              show-components: always
              show-details: always


    spring.redis.host: 10.68.177.3
    spring.redis.port: 6379
    spring.redis.password: efef1ceb-8f1b-42fb-ac50-4c2d4efa37d2
      
    spring:
      flyway:
        enabled: false
      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            jdbc.time_zone: 'Asia/Muscat'
        show-sql: 'false'
        format_sql: 'false'
      datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: '10'
          connection-init-sql: SET TIME ZONE 'Asia/Muscat'
        password: ${DB_DFSS_PASSWORD}
        username: ${DB_DFSS_USERNAME}
        url: jdbc:postgresql://10.68.176.3:5432/fuelpay
      application:
        name: dfps
      jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: 'false'
    account:
      key: ${ACCOUNT_FUELPAY_KEY}
    subsidy:
      code: '001'
    scheduler:
      fixedDelay: 30000

    logging:
      level:
        root: info
        org.hibernate.type: error

