apiVersion: v1
kind: Service
metadata:
  namespace: fuelpay
  labels:
    app: digital-fuel-scheduler-service
  name: digital-fuel-scheduler-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: default-port
  selector:
    app: digital-fuel-scheduler-service-pod
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fuelpay
  name: digital-fuel-scheduler-service-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-fuel-scheduler-service-pod
  template:
    metadata:
      labels:  
        app: digital-fuel-scheduler-service-pod
    spec:
      volumes:
        - name: volume-digital-fuel-scheduler-service
          configMap:
            name: config-digital-fuel-scheduler-service
      containers:
      - name: digital-fuel-scheduler-service
        image: gcr.io/fuel-pay-uat/digital-fuel-scheduler-service:latest
        volumeMounts:
          - name: volume-digital-fuel-scheduler-service
            mountPath: /home/
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      securityContext: {}
      terminationGracePeriodSeconds: 30  
