apiVersion: v1
kind: Service
metadata:
  namespace: fuelpay
  labels:
    app: digital-fuel-scheduler-service
  name: digital-fuel-scheduler-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: default-port
  selector:
    app: digital-fuel-scheduler-service-pod
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fuelpay
  name: digital-fuel-scheduler-service-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-fuel-scheduler-service-pod
  template:
    metadata:
      labels:  
        app: digital-fuel-scheduler-service-pod
    spec:
      volumes:
        - name: volume-digital-fuel-scheduler-service
          configMap:
            name: config-digital-fuel-scheduler-service
      containers:
      - name: digital-fuel-scheduler-service
        image: gcr.io/fuel-pay-uat/digital-fuel-scheduler-service:latest
        env:
          - name: JAVA_OPTS
            value: "-Xms256m -Xmx256m -Djava.security.egd=file:/dev/./urandom"
          - name: TIME_ZONE
            value: "-Dlogback.timezone=Asia/Muscat"
          - name: DB_FUELPAY_USERNAME
            valueFrom:
              secretKeyRef:
                name: fuel-pay-secret
                key: db-fuelpay-username
          - name: DB_FUELPAY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fuel-pay-secret
                key: db-fuelpay-password        
          - name: CARD_FUELPAY_KEYA
            valueFrom:
              secretKeyRef:
                name: fuel-pay-secret
                key: card-fuelpay-keya       
          - name: CARD_FUELPAY_KEYB
            valueFrom:
              secretKeyRef:
                name: fuel-pay-secret
                key: card-fuelpay-keyb
          - name: CARD_FUELPAY_TOKEN_KEY
            valueFrom:
              secretKeyRef:
                name: fuel-pay-secret
                key: card-fuelpay-token-key
          - name: ACCOUNT_FUELPAY_KEY
            valueFrom:
              secretKeyRef:
                name: fuel-pay-secret
                key: account-fuelpay-key         
        volumeMounts:
          - name: volume-digital-fuel-scheduler-service
            mountPath: /home/
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      securityContext: {}
      terminationGracePeriodSeconds: 30  
