steps:
  - name: gradle:6.9.2-jdk11
    entrypoint: gradle
    args: ["bootJar"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t',
           'gcr.io/$PROJECT_ID/digital-fuel-scheduler-service:$TAG_NAME',
           '-t',
           'gcr.io/$PROJECT_ID/digital-fuel-scheduler-service:latest',
           '.']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', '.k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=fuelpay-cluster-1'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/digital-fuel-scheduler-service-pod', 'digital-fuel-scheduler-service=gcr.io/$PROJECT_ID/digital-fuel-scheduler-service:$TAG_NAME', '-nfuelpay']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=fuelpay-cluster-1'
images: [
    'gcr.io/$PROJECT_ID/digital-fuel-scheduler-service:$TAG_NAME',
    'gcr.io/$PROJECT_ID/digital-fuel-scheduler-service:latest'
]
options:
  logging: CLOUD_LOGGING_ONLY
