package com.ca.scheduler.core.domain.values;

public enum CardProductType {
    DISCOUNT,PREPAID,CORPORATE,DISCOUNT_VIRTUAL,CORPORATE_TAG,PREPAID_TAG,PREPAID_VIRTUAL,CORPORATE_VIRTUAL,ATTENDANCE,ATTENDANT
}
