package com.ca.scheduler.core.domain.values;

public enum ParamName {

    STATION_NAME,
    STATION_ID,
    POS_ID,
    VAT_IN,
    SUBSIDY_RATE,
    MOGAS91_RATE,
    MOGAS95_RATE,
    DIESELGO_RATE,
    POWER98_RATE,
    POWERPLUS_RATE,
    SUBSIDY_CODE,
    FUEL_PRODUCT,
    CHECK_BALANCE,
    CHECK_OTP,
    ENABLE_VOID,
    MERCHANT_WEBSITE_URL,
    STATION_PHONE_NO,
    SUPERVISOR_PASSWORD,
    STATION_REGION,
    ENABLE_PREPAID,
    ENABLE_CORPORATE,
    ENABLE_SUBSIDY,
    ENABLE_CASH,
    ENABLE_DEBUG;
}
